In [2]:
import numpy as np
arr = np.array([12,55,23,87,4,6])
arr

array([12, 55, 23, 87,  4,  6])

In [15]:
arr = np.array([12,55,23,87,4,6, "Taining"])
arr

array(['12', '55', '23', '87', '4', '6', 'Taining'], dtype='<U21')

In [27]:
arr.dtype

dtype('<U21')

In [28]:
type(arr)

numpy.ndarray

In [29]:
arr.size # len(arr)

7

In [30]:
arr.ndim #  To check dimension of array

1

In [31]:
arr.dtype

dtype('<U21')

In [32]:
print(np.__version__)

2.0.0


In [34]:
arr = np.array([12,55,23,87,4,6])
arr[1:4]

array([55, 23, 87])

In [37]:
arr[-1] = 34

In [38]:
arr

array([12, 55, 23, 87,  4, 34])

In [39]:
arr * 2

array([ 24, 110,  46, 174,   8,  68])

<h3> 2D Array </h3>

In [41]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2.ndim

2

In [43]:
arr2.shape

(3, 3)

In [44]:
arr2[1]

array([4, 5, 6])

In [47]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr2[1,1:3]

array([5, 6])

In [50]:
arr2[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [53]:
arr2[-2:, -2:]

array([[5, 6],
       [8, 9]])

In [61]:
arr1 = np.random.randint(1, 200, 20)
arr1

array([116,  44, 104,  59,  45, 198,  20,  96,  26,  81,  48, 187, 113,
        89,  50, 141, 144,  80,  61,  96])

In [63]:
arr2 = np.random.randint(1,200, (4,5))
arr2

array([[ 15,  11,  85,  98,  77],
       [ 38,  24,  99, 110, 117],
       [ 70, 192,  88, 107, 108],
       [ 66,  50,  51,  82, 155]])