<h2>Numpy Module</h2>
<h5>NumPy stands for Numerical Python, is an open-source Python library that provides support for large, multi-dimensional arrays and matrices.<br> <br>A numpy array is like a special list in python that can hold a bunch of numbers with same data type.</h5>


In [229]:
import numpy as np

<h4>Creation of 1D array</h4>

In [230]:
arr = np.array([12,55,23,87,4,6])
arr

array([12, 55, 23, 87,  4,  6])

In [231]:
arr = np.array([12,55,23,87,4,6, "Taining"])
arr

array(['12', '55', '23', '87', '4', '6', 'Taining'], dtype='<U21')

In [232]:
arr.dtype

dtype('<U21')

In [233]:
type(arr)

numpy.ndarray

<h5>ndarray -> n dimensional array</h5>

In [234]:
arr.size # len(arr)

7

In [235]:
arr.ndim #  To check dimension of array

1

In [236]:
arr.dtype

dtype('<U21')

In [237]:
print(np.__version__)

2.0.0


In [238]:
arr = np.array([12,55,23,87,4,6])
arr[1:4]

array([55, 23, 87])

In [239]:
arr[-1] = 34

In [240]:
arr

array([12, 55, 23, 87,  4, 34])

In [241]:
arr * 2

array([ 24, 110,  46, 174,   8,  68])

<h4> 2D Array </h4>

In [242]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [243]:
type(arr2)

numpy.ndarray

In [244]:
arr2.ndim

2

In [245]:
arr2.shape

(3, 3)

In [246]:
arr2[1]

array([4, 5, 6])

In [247]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [248]:
arr2[1,1:3]

array([5, 6])

In [249]:
arr2[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [250]:
arr2[-2:, -2:]

array([[5, 6],
       [8, 9]])

In [251]:
arr1 = np.random.randint(1, 500, 100)
arr1

array([277,  43, 498,  33, 307,  54, 214, 167,  77, 406,  58, 192, 213,
       479, 400, 397, 450, 130, 176, 492, 165, 239, 356, 498, 155,  28,
       269,  81, 120, 392,  38, 257,  35, 428, 336, 413, 265,  27,  88,
        98, 291, 342, 344, 211,  73, 245, 349, 109, 207,  59, 419,  97,
       499,  59, 275, 395, 394, 167, 480,  21, 422, 474, 486, 408, 255,
       101, 182, 448, 318, 414, 127,   5, 344, 473, 381,   4, 324, 145,
       244,  48,  45, 360, 268, 216, 251, 165,  24, 476,  45, 188, 195,
       188,  53, 377,  80, 450, 153, 428, 169, 193])

In [252]:
arr2 = np.random.randint(1,200, (4,5))
arr2

array([[138,  70,  23, 125,  66],
       [ 62,  64, 133,  95,  56],
       [ 96, 123, 198,  40, 107],
       [189, 112, 122,  85,  12]])

In [253]:
# filter all those item that are less than epual to 100 and tell the number of item are present.

In [254]:
n = arr1[arr1<=100]
n

array([43, 33, 54, 77, 58, 28, 81, 38, 35, 27, 88, 98, 73, 59, 97, 59, 21,
        5,  4, 48, 45, 24, 45, 53, 80])

In [255]:
n.size

25

In [256]:
arr3 = np.zeros(5) # 1D array
arr3

array([0., 0., 0., 0., 0.])

In [257]:
arr4 = np.zeros((5, 4)) # 2D array
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [258]:
arr5 = np.ones(5)
arr5

array([1., 1., 1., 1., 1.])

In [259]:
arr5 = np.ones((5, 4)) # 2D array
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<h4>3D Array</h4>

In [260]:
arr1D = [1,2,3]
arr2D = [[1,2,3], [1,2,3], [1,2,3]]
arr3D = [[[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]]

In [261]:
arr = np.array(arr3D)
arr

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [262]:
arr.ndim

3

In [263]:
arr3 = np.random.randint(1, 500, (3, 4, 2)) #(table, row, column)
arr3

array([[[480, 443],
        [470, 409],
        [421, 471],
        [138, 299]],

       [[219, 442],
        [312, 190],
        [462, 210],
        [265, 382]],

       [[ 20, 390],
        [439, 273],
        [445, 452],
        [ 14, 348]]])

In [264]:
arr3.shape 

(3, 4, 2)

In [265]:
arr3[0:, 0, 0:]

array([[480, 443],
       [219, 442],
       [ 20, 390]])

In [266]:
arr = np.array([9, 8, 6])
arr

array([9, 8, 6])

In [267]:
min(arr)

np.int64(6)

In [268]:
np.mean(arr) #average

np.float64(7.666666666666667)

In [269]:
np.sum(arr) # Total sum of array

np.int64(23)

In [270]:
np.argmin(arr) # It returns the index of minimum item 

np.int64(2)

In [271]:
np.sort(arr)

array([6, 8, 9])